### ISSUE TITLE
/barsエンドポイントにGETメソッドでリクエストを投げるとエラーを吐く

### ISSUE THREAD

**Issue by riosuga8** [masapon06/nest-api#11]
## 内容

[現在のmasterブランチ](https://github.com/masapon06/nest-api/commit/eda8b8b56c578c8dda8398f7b2bbb70cfcced46d)で/barsエンドポイントにGETメソッドでリクエストを投げると、以下のようなエラーを吐く。

```
/Users/username/nest-api/node_modules/express/lib/response.js:766
        var charset = mime.charsets.lookup(value.split(';')[0]);
                                    ^
TypeError: Cannot read property 'lookup' of undefined
    at ServerResponse.header (/Users/username/nest-api/node_modules/express/lib/response.js:766:37)
    at ServerResponse.json (/Users/username/nest-api/node_modules/express/lib/response.js:264:10)
    at ExpressAdapter.reply (/Users/username/nest-api/node_modules/@nestjs/platform-express/adapters/express-adapter.js:29:57)
    at ExceptionsHandler.handleUnknownError (/Users/username/nest-api/node_modules/@nestjs/core/exceptions/base-exception-filter.js:38:24)
    at ExceptionsHandler.catch (/Users/username/nest-api/node_modules/@nestjs/core/exceptions/base-exception-filter.js:17:25)
    at ExceptionsHandler.next (/Users/username/nest-api/node_modules/@nestjs/core/exceptions/exceptions-handler.js:16:20)
    at /Users/username/nest-api/node_modules/@nestjs/core/router/router-proxy.js:13:35
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

## 考えられる原因
- serviceではmongoからpopulateしたデータを取得できることをログで確認しているため、mongo関連ではない。
- controllerでのnestのメソッドの使い方がよくない？
- もしくはなにか依存関係に問題がある？express, mineとエラーに出てる。
  - エラーで調べたところバージョンを更新しろ系の記事が多い。

**Comment by riosuga8** [comment]
## 解決
- 依存関係を更新
- このタイミングでnpmからyarnに移行
